{% set version = "1.14.0" %}

package:
  name: igblast
  version: "{{ version }}"

about:
  home: http://www.ncbi.nlm.nih.gov/projects/igblast/
  license: Public Domain
  summary: A tool for analyzing immunoglobulin (IG) and T cell receptor (TR) sequences.

source:
  url: ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/{{ version }}/ncbi-igblast-{{ version }}-src.tar.gz  # [linux]
  sha256: bcff2bdc2d5ad07a5699ffebed25aa79d7cc2aff58a904650ffad93eac58193f  # [linux]
  url: ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/{{ version }}/ncbi-igblast-{{ version }}-x64-macosx.tar.gz  # [osx]
  sha256: 606b293e2ecaaf355c96f0afcc0bc2a60120d7c84fd6e45a14d2cd3bc58a16e2  # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - wget
  host:
    - zlib
    - bzip2
    - libidn11
    - libxml2
    - ncbi-vdb >=2.9.6
  run:
    - zlib
    - bzip2
    - libidn11
    - libxml2
    - ncbi-vdb >=2.9.6
    - perl
    - gnutls  # [osx]

test:
  commands:
    - igblastn -h
    - igblastp -h
    - makeblastdb -h

extra:
  identifiers:
    - biotools:igblast
